name: 🐛 Signaler un bug
description: Signalez un bug pour nous aider à améliorer yNotes.
title: '[Bug]: '
labels: [bug, triage]
assignees:
  - florian-lefebvre
body:
- type: textarea
  attributes:
    label: Description du bug
    description: Une description claire et concise du bug.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Etapes à reproduire
    description: "Étapes pour reproduire le bug :"
    render: markdown
    placeholder: |
      1. [ex: Etape 1]
      2. [ex: Etape 1]
    value: |
      1. 
      2. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Comportement attendu
    description: Une description claire et concise de ce que vous attendiez.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: "Captures d'écran / vidéo"
    description: "Si possible, ajoutez des captures d'écran pour aider à expliquer votre problème."
    render: markdown
  validations:
    required: false
- type: dropdown
  id: environnemet
  attributes:
    label: Environnement
    options:
      - Beta
      - Public
  validations:
    required: true
- type: textarea
  attributes:
    label: Informations
    description: |
      Exemples :
        - **Appareil** : iPhone 6
        - **OS** : iOS 8.1
        - **Version** : 0.10.2
        - **Service scolaire** : EcoleDirecte
    value: |
        - Appareil :
        - OS :
        - Version :
        - Service scolaire :
    render: markdown
  validations:
    required: true
- type: markdown
  attributes:
    label: Context supplémentaire
    description: Des liens ? Des références ? Tout ce qui peut nous donner plus de détails sur le problème que vous rencontrez !
  validations:
    required: false
