name: 💅 Amélioration
description: Suggérez une amélioration.
title: '[Enhancement]: '
labels: [enhancement, triage]
assignees:
  - florian-lefebvre
body:
- type: textarea
  attributes:
    label: Description du problème
    description: "Ce n'est pas assez intuitif ? Un contraste n'est pas assez prononcé ?"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Description de l'amélioration"
    description: Une description claire et concise de l'amélioration.
  validations:
    required: true
- type: textarea
  attributes:
    label: Contexte supplémentaire
    description: "Ajoutez tout autre contexte ou capture d'écran permettant de clarifier votre question."
  validations:
    required: false
