# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
default_platform(:ios)
platform :ios do
    desc "Run tests"
    lane :tests do
        run_tests(scheme: "Runner")
    end
    desc "Push a new beta build to TestFlight"
    lane :beta do
        setup_ci
        match(type: "appstore", readonly: is_ci)
        build_app(workspace: "Runner.xcworkspace", scheme: "Runner") # Change name of workspace
        upload_to_testflight(changelog: ENV["CHANGELOG"] || "No changelog provided")
    end
    desc "Sets the version of the bundle to a RELEASE_VERSION passed in as an environment variable"
    lane :set_release_version do
        version = ENV["RELEASE_VERSION"]
        if version 
            UI.message("Setting version to #{version}")
            increment_version_number(version_number: version)
            increment_build_number(build_number: Time.now.to_i)
        else
            UI.user_error!("Environment variable RELEASE_VERSION not set")
        end
    end
end