name: ynotes # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Powerful school life app # 79 char long summary
description: |
  yNotes desktop app

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  dbus-ynotes: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: fr.eduwire.ynotes # adjust accordingly to your app name and
    
apps:
  ynotes:
    command: ynotes
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-ynotes
parts:
  ynotes:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application