# cd.yml
name: CD

on:
  push:
    branches:
      - deploytests

jobs:
  # CD
  deploy_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.4
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: configure gem
        run: gem i bundler -v 1.17.3
      - name: Run Fastlane setup
        run: fastlane setup
      - name: Run Fastlane
        run: fastlane closed_beta
       
