name: Tests 
on:
  push:
    branches: tests-deploy-ios
  pull_request:
    branches: tests-deploy-ios
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.x'

    - name: Cache pub dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.FLUTTER_HOME }}/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Install Flutter dependencies
      run: flutter pub get
     
    - name: Install Pods
      working-directory: ios

      run: |
        pod install
    - name: Download bundle dependencies
      run: |
        gem install bundler:2.0.2
        bundle config path vendor/bundle
        bundle install   
      working-directory: ios/fastlane

    - name: Run tests
      working-directory: ios/fastlane 
      run: |
        bundle exec fastlane tests
